### DISCUSSION TITLE
Why `"Variable Font NameVariable"`?

### DISCUSSION THREAD

**Discussion by ehzro3** [fontsource/fontsource#545] [Q&A] [answered]
```css
html {
  --serif: "FrauncesVariable", serif;
  --sans: "Roboto FlexVariable", sans-serif;
  --fixed: "Source Code ProVariable", monospace;
}
```
Like, why?
Can't we just `"Font Name Variable"` or `FontNameVariable` at least?
