### DISCUSSION TITLE
Can you customize the font output directory in Angular?

### DISCUSSION THREAD

**Discussion by dflor003** [fontsource/fontsource#892] [Q&A]
Hello! I'm trying to see if there's a way to customize the output directory of the fontsource fonts in Angular. I'm using the `@fontsource/roboto` and `@fontsource/material-icons` packages in an Angular 16 app with SCSS for styling and when I do an Angular prod build, it outputs the fonts to the root of the app next to all the generated source bundles. I prefer to serve those files out of my `/assets/fonts` folder and I was wondering if there was any out-of-the-box functionality to customize that?

An approach I'm thinking of taking is to use the SASS mixins to customize the directory and then use a custom entry in my Angular assets to manually copy the font files into that folder. I could probably get it working that way, but was looking for a more "idiomatic" way of doing this through fontsource if that exists. Any ideas?

**Comment by dflor003** [comment]
I can confirm that this works if I setup my angular project like illustrated below. I guess the only question I have is if this is the right way or if there is a better way?

In my `project.json` (Note: I'm using [NX Workspaces](https://nx.dev/))

```json
{
  "assets": [
    {
      "glob": "**/roboto-latin-[345]*",
      "input": "node_modules/@fontsource/roboto/files",
      "output": "assets/fonts"
    },
    {
      "glob": "**/*",
      "input": "node_modules/@fontsource/material-icons/files",
      "output": "assets/fonts"
    }
  ]
}
```

And then in my SCSS, I use the SCSS mixins like so:

```scss
@use 'sass:map';
@use '@fontsource/roboto/scss/mixins' as Roboto;
@use '@fontsource/material-icons/scss/mixins' as MaterialIcons;

@include Roboto.faces(
  $weights: (
    300,
    400,
    500,
  ),
  $subsets: (
    latin,
  ),
  $styles: all,
  $directory: '/assets/fonts'
);
@include MaterialIcons.faces($directory: '/assets/fonts');
```

**Reply by DanielHabenicht** [reply]
Adding the assets glob to the `angular.json` and using the following CSS I could make it work for a standard angular application: 
```scss
html {
  font-family: Roboto, "Helvetica Neue", sans-serif;
}
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```
