### ISSUE TITLE
Internal Server Error for some CJK variable fonts

### ISSUE THREAD

**Issue by Jungzl** [fontsource/fontsource#1049]
### Describe the bug

`https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-sc:vf@latest/chinese-simplified-wght-normal.woff2`
`https://cdn.jsdelivr.net/fontsource/fonts/noto-serif-sc:vf@latest/chinese-simplified-wght-normal.woff2`

which returns 
```json
{
    "status": 500,
    "error": "Bad response from download worker. {\"status\":500,\"error\":\"Could not fetch https://cdn.jsdelivr.net/npm/@fontsource-variable/noto-sans-sc@5.2.6/files/noto-sans-sc-chinese-simplified-wght-normal.woff2\",\"originalLine\":2528,\"originalColumn\":10}"
}
```

while [jsdeliver](https://cdn.jsdelivr.net/npm/@fontsource-variable/noto-sans-sc@latest/files/) has many subset fonts like `noto-sans-sc-[number]-wght-normal.woff2`

### Steps to Reproduce

1. use css snippet below:
```css
/* noto-serif-sc-chinese-simplified-wght-normal */
@font-face {
  font-family: 'Noto Serif SC Variable';
  font-style: normal;
  font-display: swap;
  font-weight: 200 900;
  src: url(https://cdn.jsdelivr.net/fontsource/fonts/noto-serif-sc:vf@latest/chinese-simplified-wght-normal.woff2) format('woff2-variations');
}
```
2. check network
