### ISSUE TITLE
Importing variable fonts with Sass

### ISSUE THREAD

**Issue by cbirdsong** [fontsource/fontsource#128]
(Continuing from #64)

I've not figured out a great way to load a variable font with the current Sass mixin. Here's what I've got in a project right now:
```scss
@use "@fontsource/raleway/scss/mixins" as Raleway;

$font-file-path: "/wp-content/themes/a-cool-theme/node_modules/";

$fontId: "raleway";
$style: normal;
@include Raleway.fontFaceCustom(
	$style: normal,
	$weight: 100 900,
	$woff2Path: $font-file-path + "@fontsource/#{$fontId}/files/#{$fontId}-latin-variable-wghtOnly-#{$style}.woff2",
	$woffPath: null,
	$unicodeRange: true
);
$style: italic;
@include Raleway.fontFaceCustom(
	$style: italic,
	$weight: 100 900,
	$woff2Path: $font-file-path + "@fontsource/#{$fontId}/files/#{$fontId}-latin-variable-wghtOnly-#{$style}.woff2",
	$woffPath: null,
	$unicodeRange: true
);
//repeat with new $fontId for other faces
```
The issues with using `fontFaceCustom`: 
- You have to manually construct the path variable. `$fontId` and `$style` have to be declared outside the `@include` so they can be used in the path variables, and `$style` again inside the mixin so it can be used by the mixin.
- There is no way to avoid including a `url() format("woff")`. (`null` produces `url("") format("woff")`.) I thought about Including a single non-variable .woff weight as a fallback, but I assume older browsers will stop parsing the `@font-face` as soon as they hit the the multi-value `font-weight`.
