### ISSUE TITLE
Material icons CSS does not contain material-icons style anymore

### ISSUE THREAD

**Issue by amanteaux** [fontsource/fontsource#152]
**Describe the bug**
In 3.1.5 version of `fontsource-material-icons`, the index.css files contains in addition to the font face source:
```css
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -moz-font-feature-settings: 'liga';
  -moz-osx-font-smoothing: grayscale;
}
```

This style is not present anymore in `@fontsource/material-icons` for version 4.2.0.
I had a look in https://github.com/fontsource/fontsource/blob/master/CHANGELOG.md and I do not find anything regarding this breaking change.

Is this change intentional?
