### ISSUE TITLE
Fonts are not loading when a subset is imported to css

### ISSUE THREAD

**Issue by abdullahe** [fontsource/fontsource#85]
Hi,

Not sure if this is a bug, but I spent a whole day trying to figure what the problem was.

I use fontsource in a Gatsby project like this:

```css
@import "~fontsource-montserrat/400.css"
@import "~fontsource-montserrat/500.css"
@import "~fontsource-montserrat/600.css"
```

But if I choose a subset as shown below, the fonts do not load on build:

```css
@import "~fontsource-montserrat/latin-ext-400.css"
@import "~fontsource-montserrat/latin-ext-500.css"
@import "~fontsource-montserrat/latin-ext-600.css"
```

For example, in 400.css files, latin-ext part is seen like this:

```css
/* montserrat-latin-ext-400-italic*/
@font-face {
  font-family: 'Montserrat';
  font-style: italic;
  font-display: swap;
  font-weight: 400;
  src: url('./files/montserrat-latin-ext-400-italic.woff2') format('woff2'), url('./files/montserrat-all-400-italic.woff') format('woff');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```

But in latin-ext-400.css it is different:

```css
/* montserrat-latin-ext-400-italic*/
@font-face {
  font-family: 'Montserrat';
  font-style: italic;
  font-display: swap;
  font-weight: 400;
  src:
    local('Montserrat Italic'),
    local('Montserrat-Italic'), 
    url('./files/montserrat-latin-ext-400-italic.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
    url('./files/montserrat-latin-ext-400-italic.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
```

In the one that is working 2 things are different. 

1- No local() test first
2- woff format file is -all- instead of -latin-ext-

This may be a bug, or something with my setup. I didn't have a chance to test on another machine. Opening this so that others won't lose hair if it happens to them. :)
