### ISSUE TITLE
Overridable font properties

### ISSUE THREAD

**Issue by ghost** [fontsource/fontsource#998]
### Describe the feature you'd like to request

Would be great if we could pass the following options down to the SCSS mixins:

- size-adjust;
- ascent-override;
- descent-override;
- line-gap-override.

This would help with e.g. alignment of different fonts, like:

``` scss
// let's say Roboto is the base font, however it does not have arabic glyphs
@include Roboto.faces(
  $subsets: (latin, latin-ext, cyrillic, cyrillic-ext, greek, greek-ext, vietnamese),
  $weights: (400, 500, 700)
);

// now let's use this one and align it with the base
@include NotoNaskhArabic.faces(
  $subsets: (arabic),
  $weights: (400, 500, 700),
  // without these the fonts are misaligned; this is what I'd like to have
  $overrides: (
    sizeAdjust: 120%,
    ascentOverride: 0%,
    descentOverride: 0%,
  )
);
```

Right now we have to copy the generated definition and set the properties ourselves.

**Comment by jwr1** [comment]
I know this wouldn't be the same as adding a whole new `$overrides` argument, but in the meantime, you could try using the [Generator Mixin](https://fontsource.org/docs/getting-started/generator-mixin).

**Comment by ghost** [comment]
@jwr1 thank you! Couldn't believe I overlooked that mixin. It totally solves the issue as there's no more copying involved.

``` scss
@use "sass:map";
@use "@fontsource/noto-naskh-arabic/scss/mixins" as NotoNaskhArabic;

@include NotoNaskhArabic.generator(
    $subsets: (arabic),
    $weights: (400, 500, 700)
  )
  using ($props) {
    $sizeAdjust: 120%;
    $ascentOverride: 0%;
    $descentOverride: 0%;

    @font-face {
      font-family: map.get($props, font-family);
      font-style: map.get($props, font-style);
      font-display: map.get($props, font-display);
      font-weight: map.get($props, font-weight);
      font-stretch: map.get($props, font-stretch);
      unicode-range: map.get($props, unicode-range);
      src: map.get($props, src);
      size-adjust: $sizeAdjust;
      ascent-override: $ascentOverride;
      descent-override: $descentOverride;
    }
  }

```
